# Generated by Django 6.1.1 on 2026-09-07 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=64)),
                ('incident_type', models.CharField(choices=[('collision', 'Collision'), ('theft', 'Theft'), ('weather', 'Weather')], max_length=16)),
                ('location', models.CharField(max_length=255)),
                ('is_drivable', models.BooleanField()),
                ('caller_name', models.CharField(blank=True, max_length=120)),
                ('injuries_reported', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('tow_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('dispatched', 'Dispatched'), ('closed', 'Closed')], default='new', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='voice_agent', max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at'], name='claims_clai_created_015674_idx')],
            },
        ),
    ]
