# Generated by Django 6.1.1 on 2026-09-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ClaimVoice FNOL Intake', max_length=120)),
                ('system_prompt', models.TextField()),
                ('greeting', models.CharField(max_length=500)),
                ('voice_id', models.CharField(choices=[('anna', 'Anna — British'), ('charles', 'Charles — British'), ('paul', 'Paul — British'), ('vera', 'Vera — British'), ('alba', 'Alba — American'), ('eve', 'Eve — American'), ('george', 'George — American'), ('jane', 'Jane — American'), ('jean', 'Jean — American'), ('mary', 'Mary — American'), ('michael', 'Michael — American'), ('giovanni', 'Giovanni — Italian'), ('lola', 'Lola — Spanish'), ('juergen', 'Juergen — German'), ('rafael', 'Rafael — Portuguese'), ('estelle', 'Estelle — French')], default='anna', max_length=32)),
                ('volume', models.PositiveSmallIntegerField(default=100)),
                ('keyterms', models.JSONField(blank=True, default=list)),
                ('vad_threshold', models.FloatField(default=0.45)),
                ('min_silence', models.PositiveIntegerField(default=700)),
                ('max_silence', models.PositiveIntegerField(default=2600)),
                ('interrupt_response', models.BooleanField(default=True)),
                ('execution_mode', models.CharField(choices=[('hold', 'Hold — Ivy waits quietly while the claim is filed'), ('interactive', 'Interactive — Ivy keeps talking while it runs')], default='hold', max_length=16)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=20)),
                ('public_base_url', models.URLField(blank=True)),
                ('agent_id', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'agent profile',
            },
        ),
    ]
