# Generated by Django 6.1.1 on 2026-09-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_agentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='severity',
            field=models.CharField(blank=True, choices=[('airbags_deployed', 'Airbags deployed'), ('fire_or_smoke', 'Fire or smoke'), ('fluid_leak', 'Fluid leak'), ('rollover', 'Rollover'), ('glass_or_dents', 'Glass or dents'), ('none', 'No major damage')], max_length=32),
        ),
        migrations.AddField(
            model_name='claim',
            name='vehicle',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
