# Generated by Django 6.1.1 on 2026-09-07 22:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_severity_claim_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('agent_id', models.CharField(blank=True, max_length=64)),
                ('channel', models.CharField(choices=[('browser', 'Browser'), ('phone', 'Phone'), ('simulator', 'Simulator')], default='browser', max_length=16)),
                ('caller_number', models.CharField(blank=True, max_length=24)),
                ('verified', models.BooleanField(default=False)),
                ('turns', models.JSONField(blank=True, default=list)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0)),
                ('close_reason', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(help_text='E.164, e.g. +15551234567', max_length=24)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('coverage', models.CharField(choices=[('liability', 'Liability only'), ('collision', 'Collision'), ('comprehensive', 'Comprehensive')], default='comprehensive', max_length=20)),
                ('deductible', models.PositiveIntegerField(default=500)),
                ('roadside_assistance', models.BooleanField(default=True)),
                ('rental_cover', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('vehicles', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.conversation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='claims.policyholder'),
        ),
        migrations.AddField(
            model_name='claim',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.policyholder'),
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=32)),
                ('phone_last4', models.CharField(max_length=8)),
                ('passed', models.BooleanField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='claims.conversation')),
                ('policyholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.policyholder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
