# Generated by Django 6.1.1 on 2026-09-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_conversation_policyholder_claim_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='recording_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
