# Generated by Django 6.1.1 on 2026-09-07 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_conversation_recording_conversation_recording_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='end_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('tow', 'Tow truck'), ('adjuster', 'Adjuster'), ('investigator', 'Theft investigator'), ('locksmith', 'Locksmith'), ('rental', 'Replacement vehicle'), ('ambulance', 'Medical')], default='tow', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('eta_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('raised_by', models.CharField(default='system', max_length=60)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='claims.claim')),
            ],
            options={
                'verbose_name_plural': 'dispatches',
                'ordering': ['-created_at'],
            },
        ),
    ]
