# Generated by Django 6.1.1 on 2026-09-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_claim_photos_handoff_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='sms_status',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
