# Generated by Django 6.1.1 on 2026-09-08 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_claim_sms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=400)),
                ('author', models.CharField(default='dispatcher', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='claims.claim')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
