# Generated by Django 6.1.1 on 2026-09-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_claim_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='redactions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
