# Generated by Django 6.1.1 on 2026-09-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_conversation_redactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='redactions',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
    ]
