# Generated by Django 6.1.1 on 2026-09-08 02:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_redactions_db_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=120)),
                ('vendor_phone', models.CharField(max_length=24)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('request', 'Request the job'), ('eta_check', 'Chase the ETA'), ('reassign', 'Reassign after a delay')], default='request', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('dialing', 'Dialing'), ('in_progress', 'In progress'), ('done', 'Completed'), ('failed', 'Failed'), ('simulated', 'Simulated')], default='queued', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('accepted', 'Accepted the job'), ('declined', 'Declined'), ('no_answer', 'No answer'), ('voicemail', 'Voicemail')], max_length=16)),
                ('eta_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=32)),
                ('provider_call_id', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_calls', to='claims.claim')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_calls', to='claims.conversation')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_calls', to='claims.dispatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
