# Generated by Django 6.1.1 on 2026-09-08 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0015_vendor_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('dispatcher', 'Dispatcher'), ('supervisor', 'Supervisor')], default='dispatcher', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(blank=True, max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('subject', models.CharField(blank=True, max_length=40)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='claims.dispatcher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Handoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('done', 'Done'), ('no_answer', 'Nobody answered'), ('after_hours', 'Out of hours'), ('abandoned', 'Caller hung up'), ('failed', 'Transfer failed')], default='waiting', max_length=16)),
                ('token', models.CharField(blank=True, db_index=True, max_length=43, unique=True)),
                ('caller_number', models.CharField(blank=True, max_length=24)),
                ('provider_call_id', models.CharField(blank=True, max_length=64)),
                ('simulated', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs', to='claims.claim')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='claims.conversation')),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs', to='claims.dispatcher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoffAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(blank=True, max_length=24)),
                ('outcome', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('no_answer', 'No answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('simulated', 'Simulated')], default='ringing', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='claims.dispatcher')),
                ('handoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='claims.handoff')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('starts', models.TimeField()),
                ('ends', models.TimeField()),
                ('dispatcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='claims.dispatcher')),
            ],
            options={
                'ordering': ['weekday', 'starts'],
            },
        ),
        migrations.AddIndex(
            model_name='handoff',
            index=models.Index(fields=['status', '-created_at'], name='claims_hand_status_8f2b2b_idx'),
        ),
    ]
