// AUTO-GENERATED by scripts/genScenes.mjs from ../script.json. Do not hand-edit;
// edit script.json and re-run the generator instead.
export type Scene = {
  id: string;
  image: string | null;
  eyebrow: string;
  title: string;
  narration: string;
  seconds: number;
  url?: string; // shown in the browser-chrome address bar when PLATFORM === "web"
};

export const FPS = 30;
export const PLATFORM: "mobile" | "web" = "web";
export const VIDEO_WIDTH = 1920;
export const VIDEO_HEIGHT = 1080;

export const APP_NAME = "ClaimVoice";
export const TAGLINE = "The AI first responder for insurance claims intake.";

export const BRAND = {
  primary: "#6366f1",
  primaryLight: "#818cf8",
  primaryDark: "#312e81",
  gold: "#fbbf24",
  silver: "#8b8b95",
  platinum: "#56565e",
  bg: "#08080a",
  surface: "#101013",
  textPrimary: "#ededf0",
  textSecondary: "#8b8b95",
  success: "#34d399",
};

export const scenes: Scene[] = [
  {
    id: "intro",
    image: null,
    eyebrow: "CLAIMVOICE",
    title: "The call is the claim.",
    narration:
      "A driver crashes, calls, and talks to Ivy. She checks they're safe, takes the policy number, and files the claim while they're still on the line.",
    seconds: 10,
  },
  {
    id: "voice",
    image: "01_voice.png",
    eyebrow: "TALK TO IVY",
    title: "One call, start to finish",
    narration:
      "Ivy runs on AssemblyAI's voice agent platform. She verifies who's calling first, then walks through what happened, where, and whether the car still drives — one question at a time.",
    seconds: 12,
    url: "claimvoice.app",
  },
  {
    id: "dashboard",
    image: "02_dashboard.png",
    eyebrow: "DISPATCHER BOARD",
    title: "Scored and triaged as it's filed",
    narration:
      "The moment Ivy files a claim, it lands here — risk score, drivability, and whether a tow is on the way, before the caller has even hung up.",
    seconds: 10,
    url: "claimvoice.app/dashboard",
  },
  {
    id: "conversations",
    image: "03_conversations.png",
    eyebrow: "EVERY CALL, KEPT",
    title: "The recording, not just the summary",
    narration:
      "Every call is transcribed and recorded in stereo — the caller on one channel, Ivy on the other — so a dispatcher can hear exactly what was said, not just what got typed.",
    seconds: 12,
    url: "claimvoice.app/dashboard",
  },
  {
    id: "dispatches",
    image: "04_dispatches.png",
    eyebrow: "GETTING A TRUCK MOVING",
    title: "The call after the call",
    narration:
      "When a car isn't drivable, a second agent rings recovery operators, ranked by distance, and updates the board the moment one accepts.",
    seconds: 10,
    url: "claimvoice.app/dashboard",
  },
  {
    id: "insights",
    image: "05_insights.png",
    eyebrow: "INSIGHTS",
    title: "Where Ivy needs to get better",
    narration:
      "Not just what happened — how the agent is doing. Which question she needs a second attempt on, most often, is the one to fix in the prompt next.",
    seconds: 10,
    url: "claimvoice.app/insights",
  },
  {
    id: "directory",
    image: "06_directory.png",
    eyebrow: "DIRECTORY",
    title: "The book Ivy verifies against",
    narration:
      "Every policyholder she can check a caller against, in one place — so a wrong answer gets refused the same way whether the policy is real or not.",
    seconds: 11,
    url: "claimvoice.app/directory",
  },
  {
    id: "share",
    image: "07_share.png",
    eyebrow: "WHAT THE DRIVER SEES",
    title: "A link, texted, that stays live",
    narration:
      "The caller gets a link back — their claim, their tow's ETA, a place to drop a photo from the roadside — updating in real time as the dispatcher works it.",
    seconds: 11,
    url: "claimvoice.app/c/...",
  },
  {
    id: "settings",
    image: "08_settings.png",
    eyebrow: "AGENT CONFIGURATION",
    title: "Ivy's whole personality, one prompt",
    narration:
      "Voice, tone, and turn-taking are all editable from here — publish a change and it's live on the next call, no redeploy required.",
    seconds: 10,
    url: "claimvoice.app/settings",
  },
  {
    id: "outro",
    image: null,
    eyebrow: "CLAIMVOICE",
    title: "Press Start. Say what happened.",
    narration:
      "One app serves the call, the board, and the dispatcher — no separate systems to keep in sync. That's ClaimVoice.",
    seconds: 8,
  },
];

export const totalSeconds = scenes.reduce((sum, s) => sum + s.seconds, 0);
