// Reads ../../script.json (the single source of truth for narration/copy)
// and writes src/scenes.ts. Re-run this any time script.json changes.
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", ".."); // walkthrough/
const script = JSON.parse(readFileSync(join(ROOT, "script.json"), "utf-8"));

const esc = (s) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

// "mobile" -> vertical phone-frame video (1080x1920). "web" -> landscape
// browser-chrome-frame video (1920x1080), for websites/web apps.
const PLATFORM = script.platform === "web" ? "web" : "mobile";
const [VIDEO_WIDTH, VIDEO_HEIGHT] = PLATFORM === "web" ? [1920, 1080] : [1080, 1920];

const sceneEntries = script.scenes
  .map(
    (s) => `  {
    id: "${s.id}",
    image: ${s.image ? `"${s.image}"` : "null"},
    eyebrow: "${esc(s.eyebrow)}",
    title: "${esc(s.title)}",
    narration:
      "${esc(s.narration)}",
    seconds: ${s.seconds},${s.url ? `\n    url: "${esc(s.url)}",` : ""}
  },`
  )
  .join("\n");

const out = `// AUTO-GENERATED by scripts/genScenes.mjs from ../script.json. Do not hand-edit;
// edit script.json and re-run the generator instead.
export type Scene = {
  id: string;
  image: string | null;
  eyebrow: string;
  title: string;
  narration: string;
  seconds: number;
  url?: string; // shown in the browser-chrome address bar when PLATFORM === "web"
};

export const FPS = 30;
export const PLATFORM: "mobile" | "web" = "${PLATFORM}";
export const VIDEO_WIDTH = ${VIDEO_WIDTH};
export const VIDEO_HEIGHT = ${VIDEO_HEIGHT};

export const APP_NAME = "${esc(script.appName)}";
export const TAGLINE = "${esc(script.tagline)}";

export const BRAND = {
  primary: "${script.brand.primary}",
  primaryLight: "${script.brand.primaryLight}",
  primaryDark: "${script.brand.primaryDark}",
  gold: "${script.brand.gold}",
  silver: "${script.brand.silver}",
  platinum: "${script.brand.platinum}",
  bg: "${script.brand.bg}",
  surface: "${script.brand.surface}",
  textPrimary: "${script.brand.textPrimary}",
  textSecondary: "${script.brand.textSecondary}",
  success: "${script.brand.success}",
};

export const scenes: Scene[] = [
${sceneEntries}
];

export const totalSeconds = scenes.reduce((sum, s) => sum + s.seconds, 0);
`;

writeFileSync(join(__dirname, "..", "src", "scenes.ts"), out);
console.log("wrote src/scenes.ts —", script.scenes.length, "scenes,", "brand:", script.appName);
